name: Run TCI Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '37 02 * * *' # 0137am daily

env:
  DB_HOST: ${{ secrets.TCI_MDB_HOST }}
  DB_USER: ${{ secrets.TCI_MDB_USER }}
  DB_PASSWORD: ${{ secrets.TCI_MDB_PASSWORD }}
  DB_NAME: ${{ secrets.TCI_MDB_NAME }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_BLOB_CONNECTION_STRING: ${{ secrets.PROD_STORAGE_CONNECTION_STRING }}
  AZURE_BLOB_IATI_CONTAINER: ${{ secrets.AZURE_BLOB_IATI_CONTAINER }}
  PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}

jobs:
  build_save:
    uses: IATI/.github/.github/workflows/build_node_save.yaml@main
    with:
      save_artifact: true
      artifact_name: build-artifact

  run-metrics:
    needs: build_save
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Unzip build artifact
        run: |
          unzip build-artifact.zip
          rm build-artifact.zip

      - name: 'Run Metrics'
        shell: bash
        run: |
          npm start
